server:
 port: 80
spring:
  application:
    name: cloud-consumer-order #服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: true
    # 是否从Eureka服务中获取已有的注册信息，默认为true。单节点无影响，集群下开启才能配合ribbon使用
    fetch-registry: true